sudo: required
services:
  - docker

before_install:
  - docker build -t sdmiller/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sdmiller/react-test npm run testCI

after_success:
  - docker build -t sdmiller/multi-client ./client
  - docker build -t sdmiller/multi-nginx ./nginx
  - docker build -t sdmiller/multi-server ./server
  - docker build -t sdmiller/multi-worker ./worker
  # Login to docker CLI
  # basically, this pipes the Docker_Password into the --password-stdin on the other side of the pipe
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sdmiller/multi-client
  - docker push sdmiller/multi-nginx
  - docker push sdmiller/multi-server
  - docker push sdmiller/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-089710905436
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

